import React, { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, CircleDollarSign, Download, Globe, RefreshCw, Radio, ShieldCheck, Trophy, Users } from 'lucide-react';
import { AnalyticsOverview, CompetitiveOverview } from '../../types';
import { tournamentXApi } from '../../services/apiClient';

const empty: AnalyticsOverview = { generatedAt: '', metrics: { tournaments: 0, activeTournaments: 0, teams: 0, matches: 0, completedMatches: 0, liveMatches: 0, completionRate: 0, totalPrizeUSD: 0 }, ranking: [], playerRanking: [], recentMatches: [] };
const emptyCompetitive: CompetitiveOverview = { generatedAt: '', integration: { esports: 'not_configured', football: 'not_configured' }, events: [], standings: [], teams: [] };

export const AnalyticsView: React.FC = () => {
  const [data, setData] = useState<AnalyticsOverview>(empty);
  const [competitive, setCompetitive] = useState<CompetitiveOverview>(emptyCompetitive);
  const [region, setRegion] = useState('Todos');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const [local, external] = await Promise.all([tournamentXApi.analytics(), tournamentXApi.competitiveOverview()]); setData(local); setCompetitive(external); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudieron cargar las estadísticas'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const maxPoints = useMemo(() => Math.max(1, ...data.ranking.map((row) => row.points)), [data.ranking]);
  const regions = useMemo(() => ['Todos', ...new Set(competitive.standings.map((standing) => standing.region))], [competitive.standings]);
  const externalStandings = useMemo(() => competitive.standings.filter((standing) => region === 'Todos' || standing.region === region), [competitive.standings, region]);
  const externalTeams = useMemo(() => competitive.teams.filter((team) => region === 'Todos' || team.region === region).slice(0, 8), [competitive.teams, region]);
  const metrics = [
    { label: 'Torneos activos', value: data.metrics.activeTournaments, helper: `${data.metrics.tournaments} totales`, icon: Trophy },
    { label: 'Equipos', value: data.metrics.teams, helper: `${data.ranking.length} clasificados`, icon: Users },
    { label: 'Partidos en vivo', value: data.metrics.liveMatches, helper: `${data.metrics.matches} programados`, icon: Radio },
    { label: 'Premios publicados', value: `$${data.metrics.totalPrizeUSD.toLocaleString()}`, helper: 'USD acumulados', icon: CircleDollarSign },
  ];
  const exportCsv = () => {
    const cells = (values: Array<string | number>) => values.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',');
    const lines = [cells(['Posición', 'Equipo', 'Región', 'PJ', 'Victorias', 'Empates', 'Derrotas', 'Winrate', 'Puntos'])];
    data.ranking.forEach((row, index) => lines.push(cells([index + 1, row.team, row.region, row.played, row.wins, row.draws, row.losses, `${row.rate}%`, row.points])));
    const blob = new Blob([`\uFEFF${lines.join('\n')}`], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = `tournamentx-ranking-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click();
    URL.revokeObjectURL(url);
  };
  return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-5 lg:space-y-7 lg:p-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="tx-kicker">INTELIGENCIA COMPETITIVA</span><h1 className="mt-2 font-brand text-3xl font-black uppercase sm:text-5xl">Rendimiento <span className="text-[#ff2e83]">competitivo</span></h1><p className="mt-2 text-sm text-slate-400">Datos calculados desde torneos, equipos y resultados registrados.</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><button onClick={exportCsv} disabled={!data.ranking.length} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2.5 text-sm font-bold hover:border-[#d6b15e]/50 disabled:opacity-40 sm:self-start sm:px-4"><Download className="w-4 h-4"/> Exportar CSV</button><button onClick={() => void load()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2.5 text-sm font-bold hover:border-[#ff2e83]/50 sm:self-start sm:px-4"><RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} /> Actualizar</button></div></div>
    {error && <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{metrics.map(({ label, value, helper, icon: Icon }) => <article key={label} className="surface rounded-2xl p-5 relative overflow-hidden"><div className="absolute -right-6 -top-8 w-24 h-24 rounded-full bg-[#ff2e83]/10 blur-2xl"/><div className="flex items-start justify-between"><div><p className="text-xs text-slate-500">{label}</p><p className="text-3xl font-black text-white mt-2">{value}</p><p className="text-[11px] text-slate-500 mt-2">{helper}</p></div><span className="w-10 h-10 rounded-xl bg-[#ff2e83]/10 border border-[#ff2e83]/20 grid place-items-center"><Icon className="w-5 h-5 text-[#ff2e83]" /></span></div></article>)}</div>
    <div className="grid xl:grid-cols-[1.55fr_.75fr] gap-6">
      <section className="surface rounded-3xl overflow-hidden"><div className="p-5 border-b border-white/10 flex items-center justify-between"><div><h2 className="font-black text-lg flex items-center gap-2"><Trophy className="w-5 h-5 text-[#ff2e83]"/> Ranking calculado</h2><p className="text-xs text-slate-500 mt-1">3 puntos por victoria, 1 por empate.</p></div><span className="text-[10px] text-emerald-400 flex gap-1"><ShieldCheck className="w-3.5 h-3.5" />DATOS VERIFICADOS</span></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500 bg-white/[.02]"><tr><th className="text-left p-4"># Equipo</th><th className="text-right p-4">PJ</th><th className="text-right p-4">V-E-D</th><th className="text-right p-4">Rendimiento</th><th className="text-right p-4">Pts</th></tr></thead><tbody>{data.ranking.map((row, index) => <tr key={row.id} className="border-t border-white/[.06] hover:bg-white/[.025]"><td className="p-4"><span className="inline-grid place-items-center w-7 h-7 rounded-lg bg-[#ff2e83]/10 text-[#ff2e83] font-black mr-3">{index + 1}</span><strong className="text-white">{row.team}</strong><span className="block ml-10 text-[10px] text-slate-600">{row.region || 'Sin región'}</span></td><td className="text-right p-4 text-slate-300">{row.played}</td><td className="text-right p-4 text-slate-400">{row.wins}-{row.draws}-{row.losses}</td><td className="text-right p-4"><div className="ml-auto w-28 h-1.5 rounded-full bg-white/10 overflow-hidden"><div className="h-full rounded-full bg-gradient-to-r from-[#ff2e83] to-[#ff75b1]" style={{ width: `${Math.max(3, row.rate)}%` }}/></div><span className="text-[10px] text-slate-500">{row.rate}%</span></td><td className="text-right p-4 font-black text-white"><span style={{ opacity: .45 + .55 * row.points / maxPoints }}>{row.points}</span></td></tr>)}</tbody></table>{!loading && data.ranking.length === 0 && <div className="p-10 text-center text-sm text-slate-500">Registra equipos y resultados para generar la clasificación.</div>}</div></section>
      <section className="surface rounded-3xl p-6"><h2 className="font-black flex items-center gap-2"><BarChart3 className="w-5 h-5 text-[#ff2e83]"/> Avance del calendario</h2><div className="mt-8 flex justify-center"><div className="relative w-44 h-44 rounded-full grid place-items-center" style={{ background: `conic-gradient(#ff2e83 ${data.metrics.completionRate * 3.6}deg, #222532 0deg)` }}><div className="w-32 h-32 rounded-full bg-[#11131b] grid place-items-center text-center"><div><div className="text-4xl font-black">{data.metrics.completionRate}%</div><div className="text-[10px] text-slate-500 uppercase">completado</div></div></div></div></div><div className="mt-8 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/[.03] p-4"><Activity className="w-4 h-4 text-emerald-400"/><strong className="block text-2xl mt-2">{data.metrics.completedMatches}</strong><span className="text-[10px] text-slate-500">Finalizados</span></div><div className="rounded-xl bg-white/[.03] p-4"><Radio className="w-4 h-4 text-red-400"/><strong className="block text-2xl mt-2">{data.metrics.liveMatches}</strong><span className="text-[10px] text-slate-500">En vivo</span></div></div><p className="text-[10px] text-slate-600 mt-5 text-center">Actualizado {data.generatedAt ? new Date(data.generatedAt).toLocaleTimeString() : '—'}</p></section>
    </div>
    <section className="surface rounded-3xl overflow-hidden">
      <div className="p-5 border-b border-white/10 flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><h2 className="font-black text-lg flex items-center gap-2"><Globe className="w-5 h-5 text-[#d6b15e]"/> Clasificaciones regionales</h2><p className="text-xs text-slate-500 mt-1">Resultados registrados en TournamentX y proveedores oficiales configurados.</p><p className="text-[10px] text-slate-600 mt-2">Esports: {competitive.integration.esports === 'configured' ? 'PandaScore API' : 'datos TournamentX'} · Fútbol: {competitive.integration.football === 'configured' ? 'football-data.org API' : 'datos TournamentX'}</p></div><div className="flex gap-2 overflow-x-auto">{regions.map((item) => <button key={item} onClick={() => setRegion(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-[10px] font-bold ${region === item ? 'bg-[#d6b15e] text-black' : 'bg-white/[.04] text-slate-400 hover:text-white'}`}>{item}</button>)}</div></div>
      <div className="grid xl:grid-cols-2 gap-4 p-4">{externalStandings.map((standing) => <article key={standing.id} className="rounded-2xl border border-white/[.07] bg-black/20 overflow-hidden"><div className="p-4 flex items-start justify-between"><div><h3 className="font-bold text-sm">{standing.competition}</h3><p className="text-[10px] text-slate-500 mt-1">{standing.sport} · {standing.region}</p></div><span className={`rounded px-2 py-1 text-[9px] font-bold ${standing.dataMode === 'api' ? 'bg-emerald-500/10 text-emerald-300' : 'bg-[#ff2e83]/10 text-[#ff69a8]'}`}>{standing.source}</span></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="text-[9px] uppercase text-slate-600"><tr><th className="p-3 text-left">Pos. Equipo</th><th className="p-3 text-right">PJ</th><th className="p-3 text-right">Pts</th><th className="p-3 text-right">Forma</th></tr></thead><tbody>{standing.table.slice(0, 8).map((row) => <tr key={row.teamId} className="border-t border-white/[.05]"><td className="p-3"><b className="text-[#d6b15e] mr-2">{row.position}</b>{row.team}</td><td className="p-3 text-right text-slate-500">{row.played}</td><td className="p-3 text-right font-bold">{row.points}</td><td className="p-3"><span className="flex justify-end gap-1">{row.form.slice(-5).map((result, index) => <i key={`${result}-${index}`} className={`not-italic grid w-4 h-4 place-items-center rounded text-[8px] ${result === 'W' ? 'bg-emerald-500/15 text-emerald-300' : result === 'L' ? 'bg-red-500/15 text-red-300' : 'bg-slate-500/15 text-slate-300'}`}>{result}</i>)}</span></td></tr>)}</tbody></table></div></article>)}</div>
    </section>
    <section className="surface rounded-3xl overflow-hidden"><div className="border-b border-white/10 p-5"><h2 className="font-black text-lg">Rendimiento individual</h2><p className="mt-1 text-xs text-slate-500">Participación calculada desde la plantilla actual y los resultados oficiales del equipo.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-[10px] uppercase text-slate-500"><tr><th className="p-4 text-left">Jugador</th><th className="p-4 text-left">Equipo</th><th className="p-4 text-right">PJ</th><th className="p-4 text-right">V-D</th><th className="p-4 text-right">Winrate</th><th className="p-4 text-right">OVR</th></tr></thead><tbody>{data.playerRanking.slice(0, 12).map((player) => <tr key={player.id} className="border-t border-white/[.06]"><td className="p-4"><strong className="text-white">{player.player}</strong><span className="block text-[10px] text-slate-500">{player.role}</span></td><td className="p-4 text-slate-400">{player.team}</td><td className="p-4 text-right">{player.played}</td><td className="p-4 text-right text-slate-400">{player.wins}-{player.losses}</td><td className="p-4 text-right font-bold text-[#ff69a8]">{player.winRate}%</td><td className="p-4 text-right font-black text-[#d6b15e]">{player.rating || '—'}</td></tr>)}</tbody></table>{!loading && data.playerRanking.length === 0 && <p className="p-8 text-center text-sm text-slate-500">Los jugadores aparecerán cuando su equipo complete un partido oficial.</p>}</div></section>
    <section className="surface rounded-3xl p-5"><div className="flex items-center justify-between"><div><h2 className="font-black text-lg flex items-center gap-2"><Users className="w-5 h-5 text-[#d6b15e]"/> Equipos y plantillas del feed</h2><p className="text-xs text-slate-500 mt-1">Los integrantes aparecen cuando el proveedor entrega la plantilla oficial.</p></div><span className="text-[10px] text-slate-600">{externalTeams.length} equipos visibles</span></div><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3 mt-5">{externalTeams.map((team) => <article key={team.id} className="rounded-2xl border border-white/[.07] bg-black/20 p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white/[.05] text-[10px] font-black">{team.shortName}</span><div className="min-w-0"><h3 className="truncate text-sm font-bold">{team.name}</h3><p className="text-[10px] text-slate-500">{team.sport} · {team.region}</p></div></div><div className="mt-3 flex gap-1">{team.form.slice(-5).map((result, index) => <span key={`${result}-${index}`} className={`grid h-5 w-5 place-items-center rounded text-[8px] font-bold ${result === 'W' ? 'bg-emerald-500/15 text-emerald-300' : result === 'L' ? 'bg-red-500/15 text-red-300' : 'bg-slate-500/15 text-slate-300'}`}>{result}</span>)}</div><p className="mt-3 text-[10px] text-slate-500">{team.players.length ? `${team.players.length} integrantes sincronizados` : 'Plantilla disponible al conectar el proveedor'}</p></article>)}</div></section>
  </div>;
};
