import React, { useEffect, useState } from 'react';
import { RefreshCw, Search, ShieldCheck, UserCog, Users } from 'lucide-react';
import { AuthUser, UserRole } from '../../types';
import { tournamentXApi } from '../../services/apiClient';

interface UsersViewProps { currentUserRole: UserRole }
const roles: Array<{ value: AuthUser['role']; label: UserRole }> = [{ value: 'admin', label: 'Admin' }, { value: 'organizer', label: 'Organizador' }, { value: 'referee', label: 'Árbitro' }, { value: 'captain', label: 'Capitán' }, { value: 'player', label: 'Jugador' }, { value: 'spectator', label: 'Espectador' }];

export const UsersView: React.FC<UsersViewProps> = ({ currentUserRole }) => {
  const [users, setUsers] = useState<AuthUser[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  const load = async () => { setLoading(true); try { setUsers((await tournamentXApi.users()).data); setMessage(''); } catch (caught) { setMessage(caught instanceof Error ? caught.message : 'No se pudieron cargar los usuarios'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const update = async (user: AuthUser, changes: Partial<AuthUser>) => { try { const body = await tournamentXApi.updateUser(user.id, changes); setUsers((current) => current.map((item) => item.id === user.id ? body.user : item)); setMessage('Permisos actualizados'); } catch (caught) { setMessage(caught instanceof Error ? caught.message : 'No se pudo actualizar'); } };
  if (currentUserRole !== 'Admin') return <div className="max-w-xl mx-auto mt-16 surface rounded-3xl p-8 text-center"><ShieldCheck className="w-10 h-10 text-[#ff2e83] mx-auto"/><h1 className="font-black text-2xl mt-4">Acceso administrativo</h1><p className="text-sm text-slate-400 mt-2">Solo un administrador puede cambiar cuentas y roles.</p></div>;
  const shown = users.filter((user) => `${user.name} ${user.email} ${user.roleLabel}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="p-5 lg:p-8 max-w-7xl mx-auto space-y-6"><header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><span className="text-[11px] tracking-[.2em] text-[#ff5ba0] font-black">IDENTIDAD Y PERMISOS</span><h1 className="font-brand text-5xl font-black uppercase italic mt-1">Usuarios y roles</h1><p className="text-sm text-slate-400 mt-2">Las cuentas derivan sus permisos del servidor.</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm"><RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`}/> Actualizar</button></header>{message && <div className="rounded-xl border border-[#ff2e83]/20 bg-[#ff2e83]/10 p-3 text-sm text-slate-200">{message}</div>}<div className="surface rounded-3xl overflow-hidden"><div className="p-4 border-b border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="flex items-center gap-2"><Users className="w-5 h-5 text-[#ff2e83]"/><strong>{users.length} cuentas</strong></div><label className="relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-500"/><input value={query} onChange={(event) => setQuery(event.target.value)} className="rounded-xl border border-white/10 bg-black/20 py-2 pl-9 pr-3 text-sm" placeholder="Buscar cuenta"/></label></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-[10px] uppercase text-slate-500 bg-white/[.02]"><tr><th className="text-left p-4">Usuario</th><th className="text-left p-4">Rol</th><th className="text-left p-4">Estado</th><th className="text-right p-4">Control</th></tr></thead><tbody>{shown.map((user) => <tr key={user.id} className="border-t border-white/[.06]"><td className="p-4"><strong className="block text-white">{user.name}</strong><span className="text-xs text-slate-500">{user.email}</span></td><td className="p-4"><select value={user.role} onChange={(event) => void update(user, { role: event.target.value as AuthUser['role'] })} className="rounded-lg border border-white/10 bg-[#141721] px-3 py-2 text-xs">{roles.map((role) => <option key={role.value} value={role.value}>{role.label}</option>)}</select></td><td className="p-4"><span className={`text-xs font-bold ${user.status === 'ACTIVE' ? 'text-emerald-400' : user.status === 'SUSPENDED' ? 'text-red-400' : 'text-slate-400'}`}>{user.status}</span></td><td className="p-4 text-right"><button onClick={() => void update(user, { status: user.status === 'SUSPENDED' ? 'ACTIVE' : 'SUSPENDED' })} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs hover:border-[#ff2e83]/50"><UserCog className="w-3.5 h-3.5"/>{user.status === 'SUSPENDED' ? 'Reactivar' : 'Suspender'}</button></td></tr>)}</tbody></table></div></div></div>;
};
